INSERT INTO BOOK ( ID , TITLE , AUTHOR) values (1 ,  'BOOK1' , 'AUTHOR1');
INSERT INTO BOOK ( ID , TITLE , AUTHOR) values ( 2, 'BOOK2' , 'AUTHOR2');
INSERT INTO BOOK ( ID, TITLE , AUTHOR) values ( 3, 'BOOK3' , 'AUTHOR3');
INSERT INTO BOOK ( ID , TITLE , AUTHOR) values ( 4, 'BOOK4' , 'AUTHOR4');